baseurl = "http://iauhs.github.io/"
languageCode = "en-us fr-fr"
title = "Iauhs与神的对话"
theme = "hyde" #default theme




[params]
    description = "Iauhs'"	#simple description on page
	disqusShortname = "iauhs" # optional
	toc = true 